name: Unit tests (nfpm)
on: 
  pull_request: {}
jobs:
  nfpm-pkg:
    timeout-minutes: 20
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./_packaging/agent/nfpm

    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v5
        with:
          PATTERNS: |
            _packaging/agent/nfpm/**
            .github/workflows/unit-tests-wix.yml
      - uses: actions/setup-go@v3
        if: env.GIT_DIFF
        with:
          go-version: '1.20'
      - uses: actions/cache@v3
        if: env.GIT_DIFF
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-nfpm-${{ hashFiles('apisrv/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-nfpm-
      - name: Mock build inputs
        if: env.GIT_DIFF
        run: |
          touch guard-linux
      - name: Build packages with nfpm
        if: env.GIT_DIFF
        run: |
          make
