name: Unit tests (agent)
on:
  pull_request: {}
jobs:
  agent:
    runs-on: ${{ matrix.sys.os }}
    strategy:
      matrix:
        sys:
          - { os: ubuntu-22.04 }
          - { os: windows-2019 }
    env:
      OS: ${{ matrix.sys.os }}
      
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: technote-space/get-diff-action@v5
        if: ${{ runner.os == 'Linux' }}
        with:
          PATTERNS: |
            go.mod
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"
      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.go-cache-paths.outputs.go-build }}
            ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-agent-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-agent-
      - name: Build apps and test suite
        run: |
          make ${{ runner.os }}
      - name: Run unit and system tests
        run: |
          make test
      - name: Run license checker
        if: ${{ runner.os == 'Linux' && contains(env.GIT_DIFF, 'go.mod') }}
        run: |
          make license-check
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: agent
          env_vars: OS
          directory: ./
